apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: <<hostname>>
  kubeletExtraArgs:
    node-ip: <<node-ip>>
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
  serviceSubnet: <<serviceSubnet>>
  podSubnet: <<podSubnet>>
  dnsDomain: <<domain>>
kubernetesVersion: <<kube_minor_version_short>>
controlPlaneEndpoint: <<controlPlaneEndpoint>>:6443
clusterName: <<cluster_name>>
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# kubelet specific options here
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
excludeCIDRs:
  - <<nodeSubnet>>