[all.vars]
kube_version = "1.28"
kube_minor_version_short = "1.28.7"
kube_minor_version = "1.28.7-1.1"
containerd_version = "1.7.13"
runc_version = "1.1.12"
cni_version = "1.4.0"
kube_vip_version = "0.6.4"
calico_version = "3.27.2"
etcd_version = "3.5.10-0"

cluster_name = "k8s-homelab"
controlPlaneEndpoint = "k8s.nevedomski.us"
domain = "nevedomski.us"
nodeSubnet = "192.168.30.0/24"
serviceSubnet = "10.96.0.0/16"
podSubnet = "10.230.0.0/24"



temp_dir = "~/TEMP/"

[all.vars.filename]
containerd = "containerd-{{ version }}-linux-amd64.tar.gz"
containerd_service = "containerd.service"
runc = "runc.amd64"
cni = "cni-plugins-linux-amd64-v{{ version }}.tgz"

[all.vars.checksumname]
containerd = "containerd-{{ version }}-linux-amd64.tar.gz.sha256sum"
runc = "runc.sha256sum"
cni = "cni-plugins-linux-amd64-v{{ version }}.tgz.sha256"

[all.vars.filelink]
containerd = "https =//github.com/containerd/containerd/releases/download/v{{ version }}/"
containerd_service = "https =//raw.githubusercontent.com/containerd/containerd/main/"
runc = "https =//github.com/opencontainers/runc/releases/download/v{{ version }}/"
cni = "https =//github.com/containernetworking/plugins/releases/download/v{{ version }}/"

[all.vars.install_path]
containerd = "/usr/local/"
containerd_service = "/usr/local/lib/systemd/system/"
runc = "/usr/local/sbin/"
cni = "/opt/cni/bin"